import assert from"node:assert/strict"
import{readFileSync}from"node:fs"
import test from"node:test"
import{LISTING_PROMPT_ID,SPECIALIZED_PROMPTS,VehicleFactsBuilder,VehicleListingEngine,VehicleListingHistoryBuilder,VehicleListingPromptBuilder,VehicleListingValidationEngine}from"@/features/vehicle-listings"
import{FakeVehicleListingProvider}from"@/features/vehicle-listings/providers/fake-listing-provider"
import type{VehicleListingContent,VehicleListingFacts,VehicleListingVersion}from"@/features/vehicle-listings"
const facts:VehicleListingFacts=new VehicleFactsBuilder().build({vehicle:{id:"vehicle-1",garageId:"garage-1",brand:"BMW",model:"M3",version:"Competition",year:2020,firstRegistrationDate:"2020-06-01",mileageKm:45000,fuel:"Essence",gearbox:"Automatique",powerDin:510,fiscalPower:42,color:"Noir",ownersCount:1,sellingPriceEuros:70000,equipment:["Sièges chauffants"]},completedWork:["Contrôle technique"],market:{medianPriceEuros:72000,score:80,summary:"Marché actif"},media:{photoCount:8,exterior360:true,interiorTour:true},garage:{name:"Garage Test",phone:"0102030405",email:"contact@example.test",city:"Paris",brandingSummary:"Spécialiste automobile"}})
const content:VehicleListingContent={premium:"BMW M3 Competition 2020, 45 000 km, 510 ch, proposée à 70 000 €. Contactez Garage Test.",leboncoin:"BMW M3 Competition de 2020. 45 000 km. Essence. Automatique. Prix : 70 000 euros.",laCentrale:"BMW M3 Competition, 45 000 km, 510 ch.",facebook:"Découvrez cette BMW M3 Competition.",instagram:"BMW M3 Competition #BMW #M3",googleBusiness:"BMW M3 disponible chez Garage Test.",short:"BMW M3 Competition disponible.",long:"BMW M3 Competition de 2020 avec 45 000 km, 510 ch et sièges chauffants.",seo:{title:"BMW M3 Competition 2020",description:"BMW M3 Competition disponible chez Garage Test.",metaDescription:"BMW M3 Competition 2020, 45 000 km, disponible chez Garage Test.",suggestedSlug:"bmw-m3-competition-2020",keywords:["BMW M3","M3 Competition"]},salesArguments:["Faible kilométrage","Sièges chauffants"],negotiationArguments:["Positionnement cohérent avec le marché"],copilotSummary:["BMW M3 Competition 2020","45 000 km","Prix affiché 70 000 €"]}
const version=(id:string,value=content):VehicleListingVersion=>({id,garageId:"garage-1",vehicleId:"vehicle-1",createdBy:"user-1",provider:"fake",model:"fake",promptId:LISTING_PROMPT_ID,promptVersion:"v1",contentHash:"a".repeat(64),format:"BUNDLE",content:value,validation:new VehicleListingValidationEngine().validate(facts,value),createdAt:"2026-08-04T10:00:00Z"})
test("VehicleFactsBuilder exposes verified public facts and no confidential fields",()=>{const serialized=JSON.stringify(facts);assert.match(serialized,/BMW/);assert.doesNotMatch(serialized,/purchasePrice|internalNotes|sellerIdentity|documents|reasonForPurchase|margin/i)})
test("prompts are versioned and prohibit invented facts",()=>{const prompt=new VehicleListingPromptBuilder().build(facts);assert.match(prompt.systemPrompt,/exclusivement les faits/i);assert.equal(SPECIALIZED_PROMPTS.leboncoin,"listing-leboncoin-v1");assert.equal(Object.keys(SPECIALIZED_PROMPTS).length,7)})
test("engine generates and validates all structured formats",async()=>{const result=await new VehicleListingEngine().generate(facts,new FakeVehicleListingProvider(content));assert.equal(result.ok,true,JSON.stringify(result));if(result.ok){assert.equal(result.validation.state,"PASS");assert.equal(result.hash.length,64)}})
test("absence of AI and provider timeout fail without persistence payload",async()=>{assert.deepEqual(await new VehicleListingEngine().generate(facts,null),{ok:false,error:"AI_DISABLED"});const timeout=await new VehicleListingEngine().generate(facts,new FakeVehicleListingProvider(null,new DOMException("Timeout","TimeoutError")));assert.equal(timeout.ok,false);if(!timeout.ok)assert.equal(timeout.error,"TIMEOUT")})
test("schema rejects an incomplete provider response",async()=>{const result=await new VehicleListingEngine().generate(facts,new FakeVehicleListingProvider({premium:"incomplet"}));assert.equal(result.ok,false);if(!result.ok)assert.equal(result.error,"INVALID_RESPONSE")})
test("validation blocks altered mileage, price, power and invented warranty",()=>{const invalid={...content,long:"BMW M3 avec 90 000 km, 600 ch, à 80 000 € et garantie constructeur 24 mois."};const result=new VehicleListingValidationEngine().validate(facts,invalid);assert.equal(result.state,"BLOCKER");assert.ok(result.blockers.some(item=>item.id==="mileage"));assert.ok(result.blockers.some(item=>item.id==="price"));assert.ok(result.blockers.some(item=>item.id==="power"));assert.ok(result.blockers.some(item=>item.id==="warranty"))})
test("history builder prepares formats, immutable versions and diff",()=>{const previous=version("old",{...content,short:"Ancienne version"});const view=new VehicleListingHistoryBuilder().build({vehicleId:"vehicle-1",vehicleName:"BMW M3",aiEnabled:true,versions:[version("new"),previous]});assert.equal(view.current?.formats.length,12);assert.ok(view.diff?.changedFields.some(item=>item.field==="Version courte"));assert.equal(view.versions[0].isCurrent,true)})
test("persistence is tenant scoped, immutable and stores hashes",()=>{const migration=readFileSync("supabase/migrations/20260804000040_create_vehicle_listing_versions.sql","utf8");const repository=readFileSync("src/features/vehicle-listings/repositories/vehicle-listing-repository.ts","utf8");assert.match(migration,/enable row level security/);assert.match(migration,/content_hash/);assert.doesNotMatch(migration,/policy .* update/i);assert.match(repository,/\.eq\("garage_id",session\.garageId\)/);assert.doesNotMatch(repository,/notes|purchase_price|documents|seller/i)})
test("UI is presentation-only and exposes accessible generation actions",()=>{const vm=new VehicleListingHistoryBuilder().build({vehicleId:"vehicle-1",vehicleName:"BMW M3",aiEnabled:true,versions:[version("new")]});const source=readFileSync("src/features/vehicle-listings/components/VehicleListingGenerator.tsx","utf8");assert.doesNotMatch(source,/supabase|vehicle_market_analyses/);assert.match(source,/aria-live/);assert.equal(vm.current?.formats[0].label,"Premium Site")})
