export const VEHICLE_LISTING_FORMATS=["PREMIUM","LEBONCOIN","LA_CENTRALE","FACEBOOK","INSTAGRAM","GOOGLE_BUSINESS","SHORT","LONG","SEO","SALES_ARGUMENTS","NEGOTIATION_ARGUMENTS","COPILOT_SUMMARY"] as const
export type VehicleListingFormat=typeof VEHICLE_LISTING_FORMATS[number]
export type VehicleListingValidationState="PASS"|"WARNING"|"BLOCKER"
export interface VehicleListingFacts { readonly vehicleId:string;readonly garageId:string;readonly identity:{readonly brand:string;readonly model:string;readonly version:string|null;readonly year:number|null;readonly firstRegistrationDate:string|null};readonly specifications:{readonly mileageKm:number|null;readonly fuel:string|null;readonly gearbox:string|null;readonly powerDin:number|null;readonly fiscalPower:number|null;readonly color:string|null;readonly ownersCount:number|null};readonly commercial:{readonly sellingPriceEuros:number|null;readonly warranty:string|null;readonly equipment:readonly string[];readonly completedWork:readonly string[];readonly services:readonly string[];readonly strengths:readonly string[];readonly weaknesses:readonly string[]};readonly market:{readonly medianPriceEuros:number|null;readonly score:number|null;readonly summary:string|null};readonly media:{readonly photoCount:number;readonly exterior360:boolean;readonly interiorTour:boolean};readonly garage:{readonly name:string;readonly phone:string|null;readonly email:string|null;readonly city:string|null;readonly brandingSummary:string|null};readonly cta:string }
export interface VehicleListingContent { readonly premium:string;readonly leboncoin:string;readonly laCentrale:string;readonly facebook:string;readonly instagram:string;readonly googleBusiness:string;readonly short:string;readonly long:string;readonly seo:{readonly title:string;readonly description:string;readonly metaDescription:string;readonly suggestedSlug:string;readonly keywords:readonly string[]};readonly salesArguments:readonly string[];readonly negotiationArguments:readonly string[];readonly copilotSummary:readonly string[] }
export interface VehicleListingValidationItem {readonly id:string;readonly state:VehicleListingValidationState;readonly message:string}
export interface VehicleListingValidation {readonly state:VehicleListingValidationState;readonly items:readonly VehicleListingValidationItem[];readonly blockers:readonly VehicleListingValidationItem[];readonly warnings:readonly VehicleListingValidationItem[]}
export interface VehicleListingVersion {readonly id:string;readonly garageId:string;readonly vehicleId:string;readonly createdBy:string;readonly provider:string;readonly model:string;readonly promptId:string;readonly promptVersion:string;readonly contentHash:string;readonly format:"BUNDLE";readonly content:VehicleListingContent;readonly validation:VehicleListingValidation;readonly createdAt:string}
export interface VehicleListingDiff {readonly previousVersionId:string|null;readonly currentVersionId:string;readonly changedFields:readonly {readonly field:string;readonly previous:string;readonly current:string}[]}
export interface VehicleListingViewModel {readonly vehicleId:string;readonly vehicleName:string;readonly aiEnabled:boolean;readonly versions:readonly {readonly id:string;readonly dateLabel:string;readonly providerLabel:string;readonly promptLabel:string;readonly isCurrent:boolean}[];readonly current:{readonly id:string;readonly formats:readonly {readonly id:VehicleListingFormat;readonly label:string;readonly content:string}[];readonly validation:VehicleListingValidation;readonly downloads:{readonly txtFilename:string;readonly markdownFilename:string}}|null;readonly diff:VehicleListingDiff|null}
export interface VehicleListingContext {readonly versionId:string|null;readonly facts:VehicleListingFacts;readonly validation:VehicleListingValidation|null;readonly salesArguments:readonly string[];readonly negotiationArguments:readonly string[];readonly summary:readonly string[]}
export type VehicleListingAnalyticsEvent="LISTING_GENERATED"|"LISTING_REGENERATED"|"LISTING_COPIED"|"LISTING_PUBLISHED"|"LISTING_RESTORED"
export interface VehicleListingProvider {readonly id:string;readonly model:string;generate(input:{readonly systemPrompt:string;readonly factsJson:string;readonly responseSchema:string;readonly timeoutMs:number}):Promise<unknown>}
