import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import{PayPlugClient,validatePayPlugConfig}from"../providers/payplug/payplug-client";import{PayPlugProvider}from"../providers/payplug/payplug-provider";import{FakePaymentProvider}from"../providers/fake-payment-provider";import{PaymentRetryEngine,PaymentVerificationEngine,verifyNotification}from"../engines/payment-engine";import{buildPaymentDashboard}from"../builders/payment-builders";import type{PaymentRecord,ProviderPayment}from"../types/payment"
const trusted:ProviderPayment={id:"pay_test",status:"PAID",amountCents:3990,currency:"EUR",isLive:false,paymentUrl:"https://secure.payplug.com/pay/test",paidAt:"2026-08-14T10:00:00Z",expiresAt:null,metadata:{garage_os_payment_id:"p",appointment_id:"a",garage_id:"g"}};const payment:PaymentRecord={id:"p",garageId:"g",appointmentId:"a",provider:"PAYPLUG",providerPaymentId:"pay_test",status:"PENDING",amountCents:3990,currency:"EUR",paymentStrategy:"FULL_PAYMENT",isLive:false,hostedPaymentUrl:trusted.paymentUrl,createdAt:"2026-08-14T09:00:00Z",paidAt:null,expiresAt:null,metadata:{}}
test("valide TEST LIVE secret et HTTPS",()=>{assert.doesNotThrow(()=>validatePayPlugConfig({enabled:true,mode:"test",secretKey:"sk_test_x",apiUrl:"https://api.payplug.com",apiVersion:"2019-08-06"}));assert.throws(()=>validatePayPlugConfig({enabled:true,mode:"live",secretKey:"sk_test_x",apiUrl:"https://api.payplug.com",apiVersion:"2019-08-06"}),/MISMATCH/);assert.throws(()=>validatePayPlugConfig({enabled:true,mode:"test",secretKey:"",apiUrl:"https://api.payplug.com",apiVersion:"2019-08-06"}),/MISSING/)})
test("crée la Hosted Payment avec montant serveur",async()=>{let body="";const fetcher:typeof fetch=async(_input,init)=>{body=String(init?.body);return new Response(JSON.stringify({id:"pay_test",amount:3990,currency:"EUR",is_live:false,is_paid:false,hosted_payment:{payment_url:trusted.paymentUrl},metadata:trusted.metadata}),{status:200})};const provider=new PayPlugProvider(new PayPlugClient({enabled:true,mode:"test",secretKey:"sk_test_x",apiUrl:"https://api.payplug.com",apiVersion:"2019-08-06"},fetcher));const result=await provider.createPayment({amountCents:3990,currency:"EUR",description:"Décalaminage -2L",customer:{firstName:"Jean",lastName:"Martin",email:"j@example.fr",phone:null},returnUrl:"https://garage.fr/return",cancelUrl:"https://garage.fr/cancel",notificationUrl:"https://garage.fr/ipn",metadata:{garage_os_payment_id:"p",appointment_id:"a",garage_id:"g"}});assert.equal(result.paymentUrl,trusted.paymentUrl);assert.match(body,/"amount":3990/);assert.match(body,/notification_url/)})
test("vérifie montant devise environnement metadata",()=>{const engine=new PaymentVerificationEngine();assert.equal(engine.verify(payment,trusted),true);assert.equal(engine.verify(payment,{...trusted,amountCents:3900}),false);assert.equal(engine.verify(payment,{...trusted,currency:"USD"}),false);assert.equal(engine.verify(payment,{...trusted,metadata:{}}),false)})
test("notification récupère le paiement serveur",async()=>assert.equal((await verifyNotification(new FakePaymentProvider(trusted),payment,trusted.id)).valid,true))
test("retry et idempotence sont déterministes",()=>{const retry=new PaymentRetryEngine();assert.equal(retry.reuse(payment),true);assert.equal(retry.canRetry({...payment,status:"FAILED"}),true);assert.equal(retry.canRetry({...payment,status:"PAID"}),false)})
test("dashboard utilise seulement les paiements réels",()=>{const summary=buildPaymentDashboard([{...payment,status:"PAID",paidAt:"2026-08-14T10:00:00Z"}],new Date("2026-08-14T12:00:00Z"));assert.equal(summary.receivedAmountToday,3990)})
test("migration garantit tenant idempotence anomalies et événements",()=>{const sql=readFileSync("supabase/migrations/20260814000046_create_payments.sql","utf8");assert.match(sql,/row level security/);assert.match(sql,/verification_mismatch/);assert.match(sql,/provider_payment_id text unique/);assert.match(sql,/payment events are immutable/);assert.match(sql,/status='CONFIRMED'/)})
test("retour navigateur ne confirme aucun paiement",()=>{const page=readFileSync("src/app/(public)/g/[garageSlug]/payment/return/page.tsx","utf8");assert.doesNotMatch(page,/update\(|apply_verified_payment/);assert.match(page,/vérification serveur/)})
