import { createClient } from "@/lib/supabase/server"
import { createPublicSupabaseClient } from "@/features/live-stock/data/public-supabase-client"
import type { RegistrationCase, RegistrationProcedureType, RegistrationRequirement } from "../types"

const caseColumns = "id,garage_id,lead_id,appointment_id,procedure_type,procedure_title,public_reference,public_token_expires_at,status,customer_name,customer_email,customer_phone,registration_number,brand,model,created_at,registration_case_requirements(id,requirement_key,label,description,is_required,display_order,status)"
function mapRequirement(row: Record<string, unknown>): RegistrationRequirement { return { id: String(row.id), requirementKey: String(row.requirement_key), label: String(row.label), description: typeof row.description === "string" ? row.description : null, isRequired: Boolean(row.is_required), displayOrder: Number(row.display_order), status: row.status as RegistrationRequirement["status"] } }
function mapCase(row: Record<string, unknown>): RegistrationCase { const raw = Array.isArray(row.registration_case_requirements) ? row.registration_case_requirements as Record<string, unknown>[] : []; return { id: String(row.id), garageId: String(row.garage_id), leadId: typeof row.lead_id === "string" ? row.lead_id : null, appointmentId: typeof row.appointment_id === "string" ? row.appointment_id : null, procedureType: row.procedure_type as RegistrationProcedureType, procedureTitle: String(row.procedure_title), publicReference: String(row.public_reference), publicTokenExpiresAt: typeof row.public_token_expires_at === "string" ? row.public_token_expires_at : null, status: row.status as RegistrationCase["status"], customerName: String(row.customer_name), customerEmail: typeof row.customer_email === "string" ? row.customer_email : null, customerPhone: typeof row.customer_phone === "string" ? row.customer_phone : null, registrationNumber: typeof row.registration_number === "string" ? row.registration_number : null, brand: typeof row.brand === "string" ? row.brand : null, model: typeof row.model === "string" ? row.model : null, createdAt: String(row.created_at), requirements: raw.map(mapRequirement).sort((a,b) => a.displayOrder-b.displayOrder) } }
export async function getRegistrationCases(garageId: string) { const { data, error } = await (await createClient()).from("registration_cases").select(caseColumns).eq("garage_id", garageId).order("created_at", { ascending: false }); if (error) throw new Error(`Lecture des dossiers impossible (${error.code}).`); return (data ?? []).map((row) => mapCase(row as unknown as Record<string, unknown>)) }
export async function getRegistrationCase(garageId: string, id: string) { const { data, error } = await (await createClient()).from("registration_cases").select(caseColumns).eq("garage_id", garageId).eq("id", id).maybeSingle(); if (error) throw new Error(`Lecture du dossier impossible (${error.code}).`); return data ? mapCase(data as unknown as Record<string, unknown>) : null }
export async function getRegistrationProcedures(garageId: string) { const db = await createClient(); const [procedures, requirements] = await Promise.all([db.from("registration_procedures").select("*").eq("garage_id", garageId).order("display_order"), db.from("registration_procedure_requirements").select("*").eq("garage_id", garageId).order("display_order")]); if (procedures.error || requirements.error) throw new Error("Lecture de la configuration Carte grise impossible."); return (procedures.data ?? []).map((procedure) => ({ ...procedure, requirements: (requirements.data ?? []).filter((item) => item.procedure_id === procedure.id) })) }
export async function getRegistrationPayments(garageId: string, appointmentId: string | null) { if (!appointmentId) return []; const { getAppointmentPayments } = await import("@/features/payments/repositories/payment-repository"); return getAppointmentPayments(garageId, appointmentId) }
export async function getRegistrationDocuments(garageId: string, caseId: string) { const { data, error } = await (await createClient()).from("registration_documents").select("id,case_requirement_id,original_name,mime_type,file_size,status,rejection_reason,uploaded_at").eq("garage_id", garageId).eq("case_id", caseId).order("uploaded_at", { ascending: false }); if (error) throw new Error(`Lecture des documents impossible (${error.code}).`); return data ?? [] }
export async function getRegistrationEvents(garageId: string, caseId: string) { const { data, error } = await (await createClient()).from("registration_case_events").select("id,event_type,old_status,new_status,created_at").eq("garage_id", garageId).eq("case_id", caseId).order("created_at", { ascending: false }); if (error) throw new Error(`Lecture de l’historique impossible (${error.code}).`); return data ?? [] }
export async function getPublicRegistrationProcedures(garageSlug:string){const{data,error}=await createPublicSupabaseClient().rpc("get_public_registration_procedures",{p_garage_slug:garageSlug});if(error)return[];return(data??[]) as readonly{procedure_type:string;title:string;description:string|null;display_order:number}[]}
export async function getRegistrationCaseLink(garageId:string,filter:{readonly appointmentId?:string;readonly leadId?:string}){let query=(await createClient()).from("registration_cases").select("id,public_reference,status").eq("garage_id",garageId);if(filter.appointmentId)query=query.eq("appointment_id",filter.appointmentId);if(filter.leadId)query=query.eq("lead_id",filter.leadId);const{data}=await query.maybeSingle();return data}
