import Link from "next/link"
import { notFound, redirect } from "next/navigation"
import { AppointmentDetailBuilder, appointmentStatusLabels, getAppointment, getAppointmentEvents, rescheduleAppointment, updateAppointmentStatus } from "@/features/scheduling"
import { getActiveGarageSession } from "@/features/tenant"
import type { AppointmentStatus } from "@/features/scheduling"

export default async function AppointmentPage({ params }: { readonly params: Promise<{ readonly appointmentId: string }> }) {
  const session = await getActiveGarageSession(); if (!session?.garageId) redirect("/login")
  const { appointmentId } = await params; const [row, events] = await Promise.all([getAppointment(session.garageId, appointmentId), getAppointmentEvents(session.garageId, appointmentId)]); if (!row) notFound()
  const detail = new AppointmentDetailBuilder().build(row)
  const actions: AppointmentStatus[] = row.status === "PENDING" || row.status === "AWAITING_PAYMENT" ? ["CONFIRMED", "CANCELLED"] : row.status === "CONFIRMED" ? ["COMPLETED", "CANCELLED", "NO_SHOW"] : []
  return <main className="space-y-6"><header><Link href="/appointments" className="text-sm underline">Retour à l’agenda</Link><h1 className="mt-3 text-3xl font-semibold">{detail.typeLabel}</h1><p>{detail.dateLabel} · {detail.durationMinutes} min · {detail.statusLabel}</p></header><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border p-5"><h2 className="text-xl font-semibold">Client</h2><p className="mt-3">{detail.customerName}</p><p>{detail.phone ?? "Téléphone non renseigné"}</p><p>{detail.email ?? "E-mail non renseigné"}</p></section><section className="rounded-xl border p-5"><h2 className="text-xl font-semibold">Suivi</h2><p className="mt-3">{detail.paymentLabel}</p>{detail.leadHref ? <Link className="underline" href={detail.leadHref}>Voir la demande client</Link> : null}</section></div><section className="rounded-xl border p-5"><h2 className="text-xl font-semibold">Déplacer le rendez-vous</h2><p className="mt-1 text-sm text-muted-foreground">Le nouveau créneau sera contrôlé atomiquement avant modification.</p><form action={rescheduleAppointment} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="appointmentId" value={row.id}/><input type="datetime-local" name="startsAt" required className="rounded-md border px-3 py-2"/><button className="rounded-md border px-4 py-2">Vérifier et déplacer</button></form></section><section className="rounded-xl border p-5"><h2 className="text-xl font-semibold">Historique</h2>{events.length ? <ol className="mt-4 space-y-2">{events.map(event => <li key={String(event.id)} className="text-sm"><strong>{String(event.event_type)}</strong> · {new Date(String(event.created_at)).toLocaleString("fr-FR")}</li>)}</ol> : <p className="mt-3 text-muted-foreground">Aucun événement.</p>}</section>{actions.length ? <section className="rounded-xl border p-5"><h2 className="text-xl font-semibold">Actions</h2><div className="mt-4 flex flex-wrap gap-3">{actions.map(status => <form key={status} action={updateAppointmentStatus}><input type="hidden" name="appointmentId" value={row.id}/><input type="hidden" name="status" value={status}/><button className="rounded-md border px-4 py-2">{appointmentStatusLabels[status]}</button></form>)}</div></section> : null}</main>
}
