import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import { PublicServiceCatalogBuilder } from "../builders/service-catalog-builders"
import { ServicePaymentRuleEngine,ServicePricingEngine,buildFinancialSnapshot } from "../engines/service-pricing-engine"
import type { ServiceOffer,ServiceOfferOption } from "../types/service-catalog"
const offer=(overrides:Partial<ServiceOffer>={}):ServiceOffer=>({id:"offer-a",garageId:"garage-a",serviceKey:"ENGINE_CLEANING",code:"UNDER_2L",name:"Décalaminage -2L",slug:"under-2l",shortDescription:null,description:null,isActive:true,isPublic:true,displayOrder:1,durationMinutes:60,pricingType:"FIXED",amountCents:3990,currency:"EUR",paymentStrategy:"FULL_PAYMENT",depositAmountCents:null,...overrides})
const option:ServiceOfferOption={id:"option-a",offerId:"offer-a",name:"Option",isActive:true,isPublic:true,amountCents:500,durationDeltaMinutes:10,displayOrder:1}
test("calcule FIXED et FULL_PAYMENT en centimes",()=>{const calculated=new ServicePricingEngine().calculate(offer(),[option],[option.id]);assert.equal(calculated.totalAmount,4490);assert.equal(new ServicePaymentRuleEngine().resolve(offer(),calculated.totalAmount).amountDueNow,4490)})
test("gère FROM QUOTE et NO_PAYMENT",()=>{assert.equal(new ServicePricingEngine().calculate(offer({pricingType:"FROM"}),[],[]).totalAmount,3990);assert.equal(new ServicePricingEngine().calculate(offer({pricingType:"QUOTE",amountCents:null}),[],[]).totalAmount,null);assert.equal(new ServicePaymentRuleEngine().resolve(offer({paymentStrategy:"NO_PAYMENT"}),3990).amountDueNow,0)})
test("gère un acompte sans inventer le total",()=>assert.deepEqual(new ServicePaymentRuleEngine().resolve(offer({amountCents:null,pricingType:"VARIABLE",paymentStrategy:"DEPOSIT",depositAmountCents:2000}),null),{paymentStrategy:"DEPOSIT",amountDueNow:2000,totalAmount:null,remainingAmount:null,currency:"EUR"}))
test("refuse une option étrangère",()=>assert.throws(()=>new ServicePricingEngine().calculate(offer(),[{...option,offerId:"other"}],[option.id]),/OPTION_NOT_AVAILABLE/))
test("fige le snapshot malgré un changement tarifaire",()=>{const initial=offer();const snapshot=buildFinancialSnapshot(initial,[],new ServicePaymentRuleEngine().resolve(initial,3990));assert.equal(snapshot.totalAmountCents,3990);assert.equal({...initial,amountCents:4490}.amountCents,4490);assert.equal(snapshot.totalAmountCents,3990)})
test("masque offre inactive et service parent inactif",()=>{const builder=new PublicServiceCatalogBuilder();assert.equal(builder.build([offer()],[option],new Set(["ENGINE_CLEANING"])).length,1);assert.equal(builder.build([offer()],[option],new Set()).length,0);assert.equal(builder.build([offer({isActive:false})],[option],new Set(["ENGINE_CLEANING"])).length,0)})
test("initialise uniquement les données SAP confirmées",()=>{const sql=readFileSync("supabase/migrations/20260814000044_create_service_catalog.sql","utf8");assert.match(sql,/3990/);assert.match(sql,/4990/);assert.match(sql,/2000/);assert.doesNotMatch(sql,/DIAGNOSTIC.*363f2dc0/i);assert.match(sql,/commercial_snapshot/);assert.match(sql,/garage_id is immutable/)})
test("ignore un montant manipulé par le client",()=>{const malicious={amount:1};assert.equal(new ServicePricingEngine().calculate(offer(),[],[]).totalAmount,3990);assert.equal(malicious.amount,1)})
