"use server"
import{createHash}from"node:crypto"
import{revalidatePath}from"next/cache"
import{createVehicleListingProvider}from"../ai"
import{VehicleListingEngine}from"../engine"
import{getVehicleListingFacts,getVehicleListingVersions,saveVehicleListingVersion}from"../repositories"
export async function generateVehicleListings(vehicleId:string){const facts=await getVehicleListingFacts(vehicleId);if(!facts)return{ok:false as const,message:"Véhicule inaccessible."};const result=await new VehicleListingEngine().generate(facts,createVehicleListingProvider());if(!result.ok){const messages={AI_DISABLED:"La génération IA n’est pas activée.",TIMEOUT:"Le fournisseur IA n’a pas répondu à temps.",PROVIDER_ERROR:"Le fournisseur IA est momentanément indisponible.",INVALID_RESPONSE:"La réponse IA est invalide.",FACT_VALIDATION_FAILED:"La génération contient une information non vérifiée."}as const;return{ok:false as const,message:messages[result.error]}}const id=await saveVehicleListingVersion({vehicleId,provider:result.provider,model:result.model,promptId:result.promptId,promptVersion:result.promptVersion,contentHash:result.hash,format:"BUNDLE",content:result.content,validation:result.validation});revalidatePath(`/stock/${vehicleId}/listings`);revalidatePath(`/stock/${vehicleId}`);return{ok:Boolean(id),message:id?"Les annonces ont été générées et validées.":"Enregistrement impossible."}}
export async function duplicateVehicleListingVersion(vehicleId:string,versionId:string){const source=(await getVehicleListingVersions(vehicleId)).find(version=>version.id===versionId);if(!source)return;await saveVehicleListingVersion({vehicleId,provider:source.provider,model:source.model,promptId:source.promptId,promptVersion:source.promptVersion,contentHash:source.contentHash,format:"BUNDLE",content:source.content,validation:source.validation,sourceVersionId:source.id});revalidatePath(`/stock/${vehicleId}/listings`)}
export async function restoreVehicleListingVersion(vehicleId:string,versionId:string){const source=(await getVehicleListingVersions(vehicleId)).find(version=>version.id===versionId);if(!source)return;const hash=createHash("sha256").update(JSON.stringify(source.content)).digest("hex");await saveVehicleListingVersion({vehicleId,provider:source.provider,model:source.model,promptId:source.promptId,promptVersion:`${source.promptVersion}-restored`,contentHash:hash,format:"BUNDLE",content:source.content,validation:source.validation,sourceVersionId:source.id});revalidatePath(`/stock/${vehicleId}/listings`)}
