export const APPOINTMENT_TYPES = ["TEST_DRIVE","ENGINE_CLEANING","REGISTRATION","CONSIGNMENT","TRADE_IN","WORKSHOP","MAINTENANCE","BODYWORK","DIAGNOSTIC","TYRES","RENTAL","OTHER"] as const
export type AppointmentType = typeof APPOINTMENT_TYPES[number]
export const APPOINTMENT_STATUSES = ["PENDING","AWAITING_PAYMENT","CONFIRMED","COMPLETED","CANCELLED","NO_SHOW"] as const
export type AppointmentStatus = typeof APPOINTMENT_STATUSES[number]
export type BusinessHoursPeriod = { readonly dayOfWeek:number; readonly opensAt:string; readonly closesAt:string }
export type CalendarException = { readonly startsAt:string; readonly endsAt:string; readonly kind:"CLOSED"|"UNAVAILABLE"|"OPEN" }
export type AppointmentTypeSetting = { readonly type:AppointmentType; readonly onlineBookingEnabled:boolean; readonly durationMinutes:number; readonly minimumNoticeMinutes:number; readonly bookingHorizonDays:number; readonly bufferBeforeMinutes:number; readonly bufferAfterMinutes:number; readonly autoConfirm:boolean; readonly paymentRequired:boolean; readonly simultaneousCapacity:number }
export type AppointmentRecord = { readonly id:string; readonly garage_id:string; readonly lead_id:string|null; readonly vehicle_id:string|null; readonly customer_id?:string|null; readonly type:AppointmentType; readonly status:AppointmentStatus; readonly starts_at:string; readonly ends_at:string; readonly timezone:string; readonly customer_name:string|null; readonly customer_phone:string|null; readonly customer_email:string|null; readonly is_historical:boolean; readonly payment_required:boolean; readonly details:Readonly<Record<string,unknown>>; readonly created_at:string }
export type AvailabilitySlot = { readonly startsAt:string; readonly endsAt:string; readonly dateLabel:string; readonly timeLabel:string }
export type AppointmentEventType = "CREATED"|"CONFIRMED"|"RESCHEDULED"|"CANCELLED"|"COMPLETED"|"NO_SHOW"|"PAYMENT_REQUIRED"
