"use client"
import { Maximize2, Minus, Plus, RotateCcw, X } from "lucide-react"
import { useEffect, useMemo, useRef, useState } from "react"
import type { InteriorTourViewerViewModel } from "../types"

const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value))
export function nextInteriorScene(currentId:string,delta:number,ids:readonly string[]){const index=ids.indexOf(currentId);return ids.length?ids[(Math.max(0,index)+delta+ids.length)%ids.length]:currentId}
export function InteriorTourViewerClient({viewer,fallbackHref="#vehicle-gallery"}:{readonly viewer:InteriorTourViewerViewModel;readonly fallbackHref?:string}){
 const [sceneId,setSceneId]=useState(viewer.startSceneId),[yaw,setYaw]=useState(0),[pitch,setPitch]=useState(0),[fov,setFov]=useState(90),[fullscreen,setFullscreen]=useState(false),[loading,setLoading]=useState(true);const drag=useRef<{x:number;y:number;yaw:number;pitch:number}|null>(null);const scene=viewer.scenes.find(item=>item.id===sceneId)??viewer.scenes[0];const ids=useMemo(()=>viewer.scenes.map(item=>item.id),[viewer.scenes]);
 useEffect(()=>{const panorama=new Image();panorama.onload=()=>setLoading(false);panorama.onerror=()=>setLoading(false);panorama.src=scene.image.source.url;return()=>{panorama.onload=null;panorama.onerror=null}},[scene.image.source.url]);
 const select=(id:string)=>{const target=viewer.scenes.find(item=>item.id===id);if(!target)return;setSceneId(id);setYaw(target.initialYaw);setPitch(target.initialPitch);setFov(target.initialFov);setLoading(true)};const reset=()=>select(scene.id);const move=(delta:number)=>select(nextInteriorScene(scene.id,delta,ids));
 return <section aria-label={viewer.label} tabIndex={0} onKeyDown={event=>{if(event.key==="ArrowLeft")setYaw(value=>value-8);if(event.key==="ArrowRight")setYaw(value=>value+8);if(event.key==="ArrowUp")setPitch(value=>clamp(value+5,-60,60));if(event.key==="ArrowDown")setPitch(value=>clamp(value-5,-60,60));if(event.key==="+")setFov(value=>clamp(value-10,30,120));if(event.key==="-")setFov(value=>clamp(value+10,30,120));if(event.key==="Escape")setFullscreen(false)}} className={fullscreen?"fixed inset-0 z-50 bg-[var(--live-background)] p-3":"relative overflow-hidden rounded-2xl border border-[var(--live-border)] bg-[var(--live-surface-muted)]"}>
  <p className="sr-only">{viewer.instructions}</p><div className={fullscreen?"relative h-[calc(100vh-6rem)]":"relative aspect-[2/1] min-h-72"} onPointerDown={event=>{drag.current={x:event.clientX,y:event.clientY,yaw,pitch};event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>{if(!drag.current)return;setYaw(drag.current.yaw-(event.clientX-drag.current.x)*.18);setPitch(clamp(drag.current.pitch+(event.clientY-drag.current.y)*.12,-60,60))}} onPointerUp={()=>{drag.current=null}}>
   <div role="img" aria-label={scene.image.alt} className="absolute inset-0 cursor-grab bg-cover bg-repeat-x active:cursor-grabbing motion-safe:transition-[background-position,background-size] motion-safe:duration-200" style={{backgroundImage:`url("${scene.image.source.url.replace(/"/g,"%22")}")`,backgroundPosition:`${50+yaw/3.6}% ${50-pitch/1.8}%`,backgroundSize:`auto ${clamp(180-fov,70,150)}%`}} />
   {loading?<span className="absolute left-3 top-3 rounded-lg bg-[var(--live-surface)] px-3 py-2 text-sm">Chargement du panorama…</span>:null}
   {scene.hotspots.map(hotspot=><button key={hotspot.id} type="button" aria-label={`${hotspot.label} — aller vers ${hotspot.targetSceneName}`} onClick={()=>select(hotspot.targetSceneId)} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full border border-[var(--live-border-strong)] bg-[var(--live-primary)] px-3 py-2 text-sm font-medium text-[var(--live-primary-foreground)] shadow-lg focus-visible:outline-2 focus-visible:outline-[var(--live-focus-ring)]" style={{left:`${hotspot.leftPercent}%`,top:`${hotspot.topPercent}%`}}>{hotspot.label}</button>)}
  </div>
  <div className="flex flex-wrap items-center gap-2 border-t border-[var(--live-border)] bg-[var(--live-surface)] p-3"><strong className="mr-auto">{scene.name}</strong><button type="button" onClick={()=>setFov(value=>clamp(value+10,30,120))} aria-label="Dézoomer" className="rounded-md p-2 focus-visible:outline-2"><Minus/></button><button type="button" onClick={()=>setFov(value=>clamp(value-10,30,120))} aria-label="Zoomer" className="rounded-md p-2 focus-visible:outline-2"><Plus/></button><button type="button" onClick={reset} aria-label={viewer.resetLabel} className="rounded-md p-2 focus-visible:outline-2"><RotateCcw/></button><button type="button" onClick={()=>setFullscreen(value=>!value)} aria-label={fullscreen?"Fermer le plein écran":viewer.fullscreenLabel} className="rounded-md p-2 focus-visible:outline-2">{fullscreen?<X/>:<Maximize2/>}</button></div>
  <div className="flex flex-wrap gap-2 p-3">{viewer.scenes.map(item=><button key={item.id} type="button" aria-pressed={item.id===scene.id} onClick={()=>select(item.id)} className="rounded-lg border border-[var(--live-border)] px-3 py-2 text-sm aria-pressed:bg-[var(--live-primary)] aria-pressed:text-[var(--live-primary-foreground)]">{item.name}</button>)}<button type="button" onClick={()=>move(1)} className="sr-only">Scène suivante</button><a href={fallbackHref} className="ml-auto rounded-lg px-3 py-2 text-sm underline">{viewer.fallbackLabel}</a></div>
 </section>
}
