import type { AssetImageViewModel } from "@/features/media"
import type { MediaQualityReport } from "@/features/media-quality"

export const INTERIOR_TOUR_STATUSES = ["DRAFT", "READY", "PUBLISHED", "FAILED", "ARCHIVED"] as const
export const INTERIOR_SCENE_STATUSES = ["UPLOADING", "READY", "EXCLUDED", "FAILED"] as const
export type InteriorTourStatus = typeof INTERIOR_TOUR_STATUSES[number]
export type InteriorSceneStatus = typeof INTERIOR_SCENE_STATUSES[number]
export type InteriorRuleState = "PASS" | "WARNING" | "BLOCKER"

export interface InteriorTourHotspot { readonly id: string; readonly garageId: string; readonly tourId: string; readonly sourceSceneId: string; readonly targetSceneId: string; readonly label: string; readonly yaw: number; readonly pitch: number; readonly createdAt: string; readonly updatedAt: string }
export interface InteriorTourScene { readonly id: string; readonly garageId: string; readonly vehicleId: string; readonly tourId: string; readonly name: string; readonly storagePath: string; readonly publicUrl: string | null; readonly position: number; readonly status: InteriorSceneStatus; readonly width: number | null; readonly height: number | null; readonly fileSize: number | null; readonly mimeType: string; readonly initialYaw: number | null; readonly initialPitch: number | null; readonly initialFov: number | null; readonly createdAt: string; readonly updatedAt: string }
export interface InteriorTour { readonly id: string; readonly garageId: string; readonly vehicleId: string; readonly status: InteriorTourStatus; readonly startSceneId: string | null; readonly isPublic: boolean; readonly createdBy: string; readonly createdAt: string; readonly updatedAt: string; readonly publishedAt: string | null; readonly scenes: readonly InteriorTourScene[]; readonly hotspots: readonly InteriorTourHotspot[] }
export interface InteriorTourRule { readonly id: string; readonly label: string; readonly state: InteriorRuleState; readonly description: string; readonly affectedSceneIds: readonly string[] }
export interface InteriorTourValidation { readonly score: number; readonly ready: boolean; readonly rules: readonly InteriorTourRule[]; readonly blockers: readonly InteriorTourRule[]; readonly warnings: readonly InteriorTourRule[]; readonly summary: string }
export interface InteriorTourViewerSceneViewModel { readonly id: string; readonly name: string; readonly image: AssetImageViewModel; readonly initialYaw: number; readonly initialPitch: number; readonly initialFov: number; readonly hotspots: readonly { readonly id: string; readonly label: string; readonly targetSceneId: string; readonly targetSceneName: string; readonly yaw: number; readonly pitch: number; readonly leftPercent: number; readonly topPercent: number }[] }
export interface InteriorTourViewerViewModel { readonly tourId: string; readonly label: string; readonly instructions: string; readonly startSceneId: string; readonly scenes: readonly InteriorTourViewerSceneViewModel[]; readonly fallbackLabel: string; readonly fullscreenLabel: string; readonly resetLabel: string }
export interface InteriorTourEditorViewModel { readonly tourId: string; readonly vehicleId: string; readonly statusLabel: string; readonly sceneCountLabel: string; readonly startSceneLabel: string; readonly publicLabel: string; readonly validation: InteriorTourValidation; readonly scenes: readonly { readonly id: string; readonly name: string; readonly position: number; readonly status: InteriorSceneStatus; readonly isStart: boolean; readonly imageUrl: string | null }[]; readonly hotspots: readonly { readonly id: string; readonly sourceLabel: string; readonly targetLabel: string; readonly label: string; readonly positionLabel: string }[]; readonly viewer: InteriorTourViewerViewModel | null; readonly mediaQuality: MediaQualityReport }
export interface InteriorTourPublicationViewModel { readonly state: "PASS" | "WARNING" | "NOT_APPLICABLE"; readonly label: string; readonly description: string; readonly href: string }
export interface InteriorTourContext { readonly status: InteriorTourStatus | null; readonly score: number | null; readonly blockers: readonly string[]; readonly warnings: readonly string[]; readonly missingViews: readonly string[]; readonly suggestedHotspots: readonly string[] }
