import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import { renderToStaticMarkup } from "react-dom/server"
import { buildInteriorTourContext,InteriorHotspotEngine,InteriorTourEngine,InteriorTourPublicationBuilder,InteriorTourSceneBuilder,InteriorTourValidationEngine,InteriorTourViewerBuilder } from "@/features/interior-tour"
import { InteriorTourViewerClient,nextInteriorScene } from "@/features/interior-tour/components/InteriorTourViewerClient"
import type { InteriorTour,InteriorTourScene } from "@/features/interior-tour"

const now="2026-08-03T10:00:00.000Z"
const scene=(id:string,position:number,overrides:Partial<InteriorTourScene>={}):InteriorTourScene=>({id,garageId:"garage-1",vehicleId:"vehicle-1",tourId:"tour-1",name:`Scène ${position}`,storagePath:`garage-1/vehicle-1/tour-1/${id}.jpg`,publicUrl:`/panorama-${id}.jpg`,position,status:"READY",width:4000,height:2000,fileSize:4_000_000,mimeType:"image/jpeg",initialYaw:0,initialPitch:0,initialFov:90,createdAt:now,updatedAt:now,...overrides})
const tour=(overrides:Partial<InteriorTour>={}):InteriorTour=>({id:"tour-1",garageId:"garage-1",vehicleId:"vehicle-1",status:"READY",startSceneId:"scene-1",isPublic:false,createdBy:"user-1",createdAt:now,updatedAt:now,publishedAt:null,scenes:[scene("scene-1",1),scene("scene-2",2)],hotspots:[{id:"hotspot-1",garageId:"garage-1",tourId:"tour-1",sourceSceneId:"scene-1",targetSceneId:"scene-2",label:"Places arrière",yaw:45,pitch:-10,createdAt:now,updatedAt:now}],...overrides})
test("creates an immutable deterministic interior tour workflow",()=>{const engine=new InteriorTourEngine();assert.equal(engine.canTransition("DRAFT","READY"),true);assert.equal(engine.canTransition("DRAFT","PUBLISHED"),false);assert.throws(()=>engine.assertTransition("DRAFT","PUBLISHED"));assert.equal(engine.canTransition("PUBLISHED","READY"),true)})
test("orders and moves scenes without mutation",()=>{const source=[scene("two",2),scene("one",1)];const moved=new InteriorTourEngine().move(source,"one",1);assert.deepEqual(moved.map(item=>item.id),["two","one"]);assert.deepEqual(source.map(item=>item.id),["two","one"])})
test("validates start scene, 2:1 ratio, resolution and readiness",()=>{const valid=new InteriorTourValidationEngine().validate(tour());assert.equal(valid.ready,true);assert.equal(valid.score,100);const invalid=new InteriorTourValidationEngine().validate(tour({startSceneId:"foreign",scenes:[scene("scene-1",1,{width:1200,height:900})]}));assert.equal(invalid.ready,false);assert.ok(invalid.blockers.some(item=>item.id==="start"));assert.ok(invalid.warnings.some(item=>item.id==="ratio"));assert.ok(invalid.warnings.some(item=>item.id==="resolution"))})
test("rejects an invalid or cross-tenant hotspot",()=>{const engine=new InteriorHotspotEngine();const valid=tour().hotspots[0];assert.equal(engine.validate(valid,tour().scenes),true);assert.equal(engine.validate({...valid,targetSceneId:"foreign"},tour().scenes),false);assert.equal(engine.validate({...valid,targetSceneId:valid.sourceSceneId},tour().scenes),false)})
test("builds back-office, public viewer, media quality and copilot context",()=>{const editor=new InteriorTourSceneBuilder().build(tour(),"BMW M3");assert.equal(editor.scenes.length,2);assert.equal(editor.viewer?.startSceneId,"scene-1");assert.ok(editor.mediaQuality.score>=0);const context=buildInteriorTourContext(tour());assert.equal(context.status,"READY");assert.ok(Array.isArray(context.missingViews))})
test("publication is optional, warning or pass",()=>{const builder=new InteriorTourPublicationBuilder();assert.equal(builder.build(null,"vehicle-1").state,"NOT_APPLICABLE");assert.equal(builder.build(tour(),"vehicle-1").state,"WARNING");assert.equal(builder.build(tour({status:"PUBLISHED",isPublic:true}),"vehicle-1").state,"PASS")})
test("viewer supports scene navigation, keyboard instructions and photo fallback",()=>{const viewer=new InteriorTourViewerBuilder().build(tour(),"BMW M3");assert.ok(viewer);assert.equal(nextInteriorScene("scene-1",1,["scene-1","scene-2"]),"scene-2");const html=renderToStaticMarkup(<InteriorTourViewerClient viewer={viewer!}/>);assert.match(html,/Visite intérieure panoramique/);assert.match(html,/Places arrière/);assert.match(html,/Voir les photos classiques/);assert.match(html,/tabindex="0"/)})
test("public projection is restrictive and storage remains private",()=>{const migration=readFileSync("supabase/migrations/20260803000039_create_interior_tour_experience.sql","utf8");assert.match(migration,/public_live_interior_tours/);assert.match(migration,/t.status='PUBLISHED'/);assert.match(migration,/v.publication_status='PUBLISHED'/);assert.match(migration,/g.live_enabled=true/);assert.match(migration,/vehicle-interior-tours','vehicle-interior-tours',false/);assert.match(migration,/garage_id::text=\(storage.foldername\(name\)\)\[1\]/)})
test("repository scopes private reads to the active garage",()=>{const source=readFileSync("src/features/interior-tour/repositories/interior-tour-repository.ts","utf8");assert.match(source,/\.eq\("garage_id",session\.garageId\)/);assert.match(source,/createSignedUrl/);assert.doesNotMatch(source,/service_role/)})
test("React components contain presentation and interaction only",()=>{const workspace=readFileSync("src/features/interior-tour/components/InteriorTourWorkspace.tsx","utf8");const viewer=readFileSync("src/features/interior-tour/components/InteriorTourViewerClient.tsx","utf8");assert.doesNotMatch(workspace,/supabase|\.sort\(|\.filter\(/i);assert.doesNotMatch(viewer,/supabase|garage_members|interior_tours/i)})
