import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import{renderToStaticMarkup}from"react-dom/server";import{AppointmentAvailabilityEngine,AppointmentBookingEngine,AppointmentStatusEngine}from"../engine/scheduling-engine";import{AppointmentCalendarBuilder,PublicBookingBuilder}from"../builders/scheduling-builders";import{PublicSlotSelector}from"../components/PublicSlotSelector";import type{AppointmentRecord,AppointmentTypeSetting}from"../types/scheduling"
const setting=(overrides:Partial<AppointmentTypeSetting>={}):AppointmentTypeSetting=>({type:"TEST_DRIVE",onlineBookingEnabled:true,durationMinutes:30,minimumNoticeMinutes:0,bookingHorizonDays:30,bufferBeforeMinutes:0,bufferAfterMinutes:0,autoConfirm:false,paymentRequired:false,simultaneousCapacity:1,...overrides})
const engine=new AppointmentAvailabilityEngine();const base={from:new Date("2026-08-17T00:00:00Z"),to:new Date("2026-08-17T23:59:00Z"),timezone:"Europe/Paris",hours:[{dayOfWeek:1,opensAt:"09:00",closesAt:"11:00"}],exceptions:[],appointments:[],setting:setting(),now:new Date("2026-08-16T00:00:00Z")}
test("calcule les horaires, durées, délai et horizon sans mutation",()=>{const slots=engine.build(base);assert.deepEqual(slots,["2026-08-17T09:00:00.000Z","2026-08-17T09:30:00.000Z","2026-08-17T10:00:00.000Z","2026-08-17T10:30:00.000Z"]);assert.equal(base.hours.length,1);assert.equal(engine.build({...base,setting:setting({minimumNoticeMinutes:3000})}).length,0)})
test("garage fermé et réservation désactivée ne produisent aucun créneau",()=>{assert.deepEqual(engine.build({...base,hours:[]}),[]);assert.deepEqual(engine.build({...base,setting:setting({onlineBookingEnabled:false})}),[])})
test("exceptions, buffers et capacité filtrent les collisions",()=>{const blocked=engine.build({...base,exceptions:[{kind:"CLOSED"as const,startsAt:"2026-08-17T09:30:00Z",endsAt:"2026-08-17T10:00:00Z"}],appointments:[{startsAt:"2026-08-17T10:00:00Z",endsAt:"2026-08-17T10:30:00Z"}],setting:setting({bufferBeforeMinutes:15})});assert.deepEqual(blocked,["2026-08-17T09:00:00.000Z"]);assert.ok(engine.build({...base,appointments:[{startsAt:"2026-08-17T09:00:00Z",endsAt:"2026-08-17T09:30:00Z"}],setting:setting({simultaneousCapacity:2})}).includes("2026-08-17T09:00:00.000Z"))})
test("détermine PENDING CONFIRMED et AWAITING_PAYMENT",()=>{const booking=new AppointmentBookingEngine();assert.equal(booking.initialStatus(setting()),"PENDING");assert.equal(booking.initialStatus(setting({autoConfirm:true})),"CONFIRMED");assert.equal(booking.initialStatus(setting({paymentRequired:true,autoConfirm:true})),"AWAITING_PAYMENT")})
test("refuse les transitions arbitraires",()=>{const status=new AppointmentStatusEngine();assert.equal(status.canTransition("PENDING","CONFIRMED"),true);assert.equal(status.canTransition("PENDING","COMPLETED"),false);assert.equal(status.canTransition("CONFIRMED","NO_SHOW"),true)})
test("builders agenda dashboard public préparent la présentation",()=>{const row={id:"a",garage_id:"g",lead_id:"l",vehicle_id:"v",type:"TEST_DRIVE",status:"PENDING",starts_at:"2026-08-17T09:00:00Z",ends_at:"2026-08-17T09:30:00Z",timezone:"Europe/Paris",customer_name:"Jean Martin",customer_phone:"0600000000",customer_email:null,payment_required:false,details:{},created_at:"2026-08-16T00:00:00Z"}as const satisfies AppointmentRecord;assert.equal(new AppointmentCalendarBuilder().build([row])[0].href,"/appointments/a");const slots=new PublicBookingBuilder().build([{starts_at:row.starts_at,ends_at:row.ends_at,local_date:"2026-08-17",local_time:"11:00:00"}]);assert.match(renderToStaticMarkup(<PublicSlotSelector slots={slots}/>),/appointmentStartsAt|Choisissez votre rendez-vous/)})
test("la migration garantit atomicité concurrence RLS et confidentialité",()=>{const sql=readFileSync("supabase/migrations/20260814000043_create_scheduling_platform.sql","utf8");for(const token of["pg_advisory_xact_lock","simultaneous_capacity","enable row level security","security definer","revoke all","garage_members","submission_fingerprint","APPOINTMENT_BOOKED","PAYMENT_REQUIRED","RESCHEDULED"])assert.match(sql,new RegExp(token,"i"));assert.doesNotMatch(sql,/insert into public\.garage_business_hours/)})
test("services inactifs, véhicule non publié et agenda absent sont refusés",()=>{const sql=readFileSync("supabase/migrations/20260814000043_create_scheduling_platform.sql","utf8");assert.match(sql,/garage_services[\s\S]*is_enabled/);assert.match(sql,/publication_status='PUBLISHED'/);assert.match(sql,/schedule_unavailable|booking_disabled/)})
test("routes, navigation, notifications et dashboard sont intégrés",()=>{assert.match(readFileSync("src/components/layout/sidebar.tsx","utf8"),/Agenda/);assert.match(readFileSync("src/app/(dashboard)/dashboard/page.tsx","utf8"),/AppointmentDashboardSignal/);const sql=readFileSync("supabase/migrations/20260814000043_create_scheduling_platform.sql","utf8");assert.match(sql,/Rendez-vous à confirmer|Nouveau rendez-vous/);assert.match(readFileSync("src/app/(dashboard)/appointments/[appointmentId]/page.tsx","utf8"),/Déplacer le rendez-vous/)})
