import "server-only"
import { getActiveGarageSession } from "@/features/tenant"
import { createClient } from "@/lib/supabase/server"
import type { InteriorTour, InteriorTourHotspot, InteriorTourScene, InteriorTourStatus } from "../types"

type SceneRow = { id:string;garage_id:string;vehicle_id:string;tour_id:string;name:string;storage_path:string;position:number;status:InteriorTourScene["status"];width:number|null;height:number|null;file_size:number|null;mime_type:string;initial_yaw:number|null;initial_pitch:number|null;initial_fov:number|null;created_at:string;updated_at:string }
type HotspotRow = { id:string;garage_id:string;tour_id:string;source_scene_id:string;target_scene_id:string;label:string;yaw:number;pitch:number;created_at:string;updated_at:string }
type TourRow = { id:string;garage_id:string;vehicle_id:string;status:InteriorTourStatus;start_scene_id:string|null;is_public:boolean;created_by:string;created_at:string;updated_at:string;published_at:string|null;interior_tour_scenes:SceneRow[]|null;interior_tour_hotspots:HotspotRow[]|null }
const SELECT = "id,garage_id,vehicle_id,status,start_scene_id,is_public,created_by,created_at,updated_at,published_at,interior_tour_scenes(id,garage_id,vehicle_id,tour_id,name,storage_path,position,status,width,height,file_size,mime_type,initial_yaw,initial_pitch,initial_fov,created_at,updated_at),interior_tour_hotspots(id,garage_id,tour_id,source_scene_id,target_scene_id,label,yaw,pitch,created_at,updated_at)"
const mapHotspot = (row:HotspotRow):InteriorTourHotspot => ({ id:row.id,garageId:row.garage_id,tourId:row.tour_id,sourceSceneId:row.source_scene_id,targetSceneId:row.target_scene_id,label:row.label,yaw:Number(row.yaw),pitch:Number(row.pitch),createdAt:row.created_at,updatedAt:row.updated_at })
function mapScene(row:SceneRow, publicUrl:string|null):InteriorTourScene { return { id:row.id,garageId:row.garage_id,vehicleId:row.vehicle_id,tourId:row.tour_id,name:row.name,storagePath:row.storage_path,publicUrl,position:row.position,status:row.status,width:row.width,height:row.height,fileSize:row.file_size,mimeType:row.mime_type,initialYaw:row.initial_yaw===null?null:Number(row.initial_yaw),initialPitch:row.initial_pitch===null?null:Number(row.initial_pitch),initialFov:row.initial_fov===null?null:Number(row.initial_fov),createdAt:row.created_at,updatedAt:row.updated_at } }
async function mapTour(row:TourRow):Promise<InteriorTour> { const supabase=await createClient(); const scenes=await Promise.all((row.interior_tour_scenes??[]).map(async scene=>{ const {data}=await supabase.storage.from("vehicle-interior-tours").createSignedUrl(scene.storage_path,3600); return mapScene(scene,data?.signedUrl??null) })); return { id:row.id,garageId:row.garage_id,vehicleId:row.vehicle_id,status:row.status,startSceneId:row.start_scene_id,isPublic:row.is_public,createdBy:row.created_by,createdAt:row.created_at,updatedAt:row.updated_at,publishedAt:row.published_at,scenes,hotspots:(row.interior_tour_hotspots??[]).map(mapHotspot) } }
export async function getInteriorTour(vehicleId:string):Promise<InteriorTour|null> { const session=await getActiveGarageSession(); if(!session?.garageId)return null; const supabase=await createClient(); const {data,error}=await supabase.from("interior_tours").select(SELECT).eq("garage_id",session.garageId).eq("vehicle_id",vehicleId).neq("status","ARCHIVED").maybeSingle(); if(error)throw new Error(`Lecture de la visite intérieure impossible (${error.code}).`); return data?mapTour(data as unknown as TourRow):null }
export async function getPublicInteriorTour(garageId:string,vehicleId:string):Promise<InteriorTour|null> { const supabase=await createClient(); const [{data:scenes,error},{data:hotspots}]=await Promise.all([supabase.from("public_live_interior_tours").select("*").eq("garage_id",garageId).eq("vehicle_id",vehicleId).order("position"),supabase.from("public_live_interior_hotspots").select("*").eq("garage_id",garageId)]); if(error||!scenes?.length)return null; const rows=scenes as unknown as Array<{tour_id:string;garage_id:string;vehicle_id:string;start_scene_id:string|null;published_at:string|null;scene_id:string;name:string;storage_path:string;position:number;width:number|null;height:number|null;mime_type:string;initial_yaw:number|null;initial_pitch:number|null;initial_fov:number|null}>; const tourId=rows[0].tour_id; const now=new Date(0).toISOString(); const mappedScenes=await Promise.all(rows.map(async row=>{ const {data}=await supabase.storage.from("vehicle-interior-tours").createSignedUrl(row.storage_path,3600); return { id:row.scene_id,garageId,vehicleId,tourId,name:row.name,storagePath:row.storage_path,publicUrl:data?.signedUrl??null,position:row.position,status:"READY" as const,width:row.width,height:row.height,fileSize:null,mimeType:row.mime_type,initialYaw:row.initial_yaw,initialPitch:row.initial_pitch,initialFov:row.initial_fov,createdAt:now,updatedAt:now } })); return { id:tourId,garageId,vehicleId,status:"PUBLISHED",startSceneId:rows[0].start_scene_id,isPublic:true,createdBy:"",createdAt:now,updatedAt:now,publishedAt:rows[0].published_at,scenes:mappedScenes,hotspots:((hotspots??[]) as unknown as HotspotRow[]).filter(item=>item.tour_id===tourId).map(mapHotspot) } }
