import { createClient } from "@/lib/supabase/server"
import type { ServiceOffer, ServiceOfferOption } from "../types/service-catalog"

const mapOffer = (row: Record<string, unknown>): ServiceOffer => ({ id:String(row.id),garageId:String(row.garage_id),serviceKey:String(row.service_key),code:String(row.code),name:String(row.name),slug:String(row.slug),shortDescription:typeof row.short_description==="string"?row.short_description:null,description:typeof row.description==="string"?row.description:null,isActive:Boolean(row.is_active),isPublic:Boolean(row.is_public),displayOrder:Number(row.display_order),durationMinutes:row.duration_minutes===null?null:Number(row.duration_minutes),pricingType:row.pricing_type as ServiceOffer["pricingType"],amountCents:row.amount_cents===null?null:Number(row.amount_cents),currency:String(row.currency),paymentStrategy:row.payment_strategy as ServiceOffer["paymentStrategy"],depositAmountCents:row.deposit_amount_cents===null?null:Number(row.deposit_amount_cents) })
const mapOption = (row: Record<string, unknown>): ServiceOfferOption => ({ id:String(row.id),offerId:String(row.offer_id),name:String(row.name),isActive:Boolean(row.is_active),isPublic:Boolean(row.is_public),amountCents:row.amount_cents===null?null:Number(row.amount_cents),durationDeltaMinutes:Number(row.duration_delta_minutes),displayOrder:Number(row.display_order) })

export async function getServiceCatalog(garageId: string) { const db=await createClient();const [offers,options]=await Promise.all([db.from("service_offers").select("*").eq("garage_id",garageId).order("display_order"),db.from("service_offer_options").select("*").eq("garage_id",garageId).order("display_order")]);if(offers.error||options.error)throw new Error("Lecture du catalogue impossible.");return{offers:(offers.data??[]).map(row=>mapOffer(row)),options:(options.data??[]).map(row=>mapOption(row))} }
export async function saveServiceOffer(garageId:string,input:Omit<ServiceOffer,"garageId">){const{error}=await(await createClient()).from("service_offers").upsert({id:input.id,garage_id:garageId,service_key:input.serviceKey,code:input.code,name:input.name,slug:input.slug,short_description:input.shortDescription,description:input.description,is_active:input.isActive,is_public:input.isPublic,display_order:input.displayOrder,duration_minutes:input.durationMinutes,pricing_type:input.pricingType,amount_cents:input.amountCents,currency:input.currency,payment_strategy:input.paymentStrategy,deposit_amount_cents:input.depositAmountCents,updated_at:new Date().toISOString()});return !error}
export async function resolveServerPricing(garageId:string,offerSlug:string,selectedOptionIds:readonly string[]){const catalog=await getServiceCatalog(garageId);const offer=catalog.offers.find(item=>item.slug===offerSlug&&item.isActive);if(!offer)throw new Error("OFFER_NOT_AVAILABLE");const{ServicePricingEngine,ServicePaymentRuleEngine,buildFinancialSnapshot}=await import("../engines/service-pricing-engine");const calculated=new ServicePricingEngine().calculate(offer,catalog.options,selectedOptionIds);const payment=new ServicePaymentRuleEngine().resolve(offer,calculated.totalAmount);return{offer,payment,snapshot:buildFinancialSnapshot(offer,calculated.selected,payment)}}
