create table public.payments(id uuid primary key default gen_random_uuid(),garage_id uuid not null references public.garages(id) on delete cascade,appointment_id uuid not null references public.appointments(id) on delete restrict,provider text not null,provider_payment_id text unique,status text not null check(status in('CREATED','PENDING','PAID','FAILED','CANCELLED','EXPIRED','PARTIALLY_REFUNDED','REFUNDED')),amount_cents integer not null check(amount_cents>0),currency text not null check(currency~'^[A-Z]{3}$'),payment_strategy text not null check(payment_strategy in('FULL_PAYMENT','DEPOSIT')),is_live boolean not null,hosted_payment_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),paid_at timestamptz,failed_at timestamptz,cancelled_at timestamptz,expired_at timestamptz,expires_at timestamptz,metadata jsonb not null default'{}',constraint payment_metadata_bounded check(jsonb_typeof(metadata)='object'and octet_length(metadata::text)<=8192));
create index payments_garage_status_idx on public.payments(garage_id,status,created_at desc);create index payments_appointment_idx on public.payments(appointment_id,created_at desc);
create table public.payment_events(id uuid primary key default gen_random_uuid(),garage_id uuid not null references public.garages(id) on delete cascade,payment_id uuid not null references public.payments(id) on delete cascade,appointment_id uuid not null references public.appointments(id) on delete cascade,actor_id uuid references auth.users(id),provider text not null,event_type text not null check(event_type in('CREATED','PAYMENT_PAGE_CREATED','PAID','FAILED','CANCELLED','EXPIRED','REFUND_REQUESTED','PARTIALLY_REFUNDED','REFUNDED','ANOMALY')),metadata jsonb not null default'{}',created_at timestamptz not null default now(),constraint payment_event_metadata_bounded check(jsonb_typeof(metadata)='object'and octet_length(metadata::text)<=4096));
create unique index payment_events_terminal_once on public.payment_events(payment_id,event_type) where event_type in('PAID','FAILED','CANCELLED','EXPIRED','REFUNDED');
create function public.enforce_payment_tenant()returns trigger language plpgsql set search_path=public as $$ begin if tg_op='UPDATE'and new.garage_id is distinct from old.garage_id then raise exception'garage_id is immutable';end if;if not exists(select 1 from appointments a where a.id=new.appointment_id and a.garage_id=new.garage_id)then raise exception'appointment tenant mismatch';end if;return new;end $$;
create trigger enforce_payment_tenant before insert or update on public.payments for each row execute function public.enforce_payment_tenant();
create function public.prevent_payment_event_mutation()returns trigger language plpgsql as $$ begin raise exception'payment events are immutable';end $$;create trigger payment_events_immutable before update or delete on public.payment_events for each row execute function public.prevent_payment_event_mutation();
alter table public.payments enable row level security;alter table public.payment_events enable row level security;
create policy"Members read payments"on public.payments for select to authenticated using(exists(select 1 from garage_members gm where gm.garage_id=payments.garage_id and gm.user_id=auth.uid()));
create policy"Members read payment events"on public.payment_events for select to authenticated using(exists(select 1 from garage_members gm where gm.garage_id=payment_events.garage_id and gm.user_id=auth.uid()));

create function public.apply_verified_payment(p_payment_id uuid,p_provider_id text,p_status text,p_amount integer,p_currency text,p_is_live boolean,p_paid_at timestamptz,p_metadata jsonb)returns text language plpgsql security definer set search_path=public,pg_temp as $$ declare p payments%rowtype;a appointments%rowtype;event_name text;begin select*into p from payments where id=p_payment_id for update;if p.id is null then return'not_found';end if;if p.provider_payment_id<>p_provider_id or p.amount_cents<>p_amount or p.currency<>p_currency or p.is_live<>p_is_live or coalesce(p_metadata->>'garage_os_payment_id','')<>p.id::text or coalesce(p_metadata->>'appointment_id','')<>p.appointment_id::text or coalesce(p_metadata->>'garage_id','')<>p.garage_id::text then insert into payment_events(garage_id,payment_id,appointment_id,provider,event_type,metadata)values(p.garage_id,p.id,p.appointment_id,p.provider,'ANOMALY',jsonb_build_object('reason','verification_mismatch'));return'mismatch';end if;if p.status=p_status then return'idempotent';end if;if p.status='PAID'and p_status<>'REFUNDED' then return'already_paid';end if;event_name:=case when p_status in('PAID','FAILED','CANCELLED','EXPIRED','PARTIALLY_REFUNDED','REFUNDED')then p_status else null end;if event_name is null then return'ignored';end if;update payments set status=p_status,paid_at=case when p_status='PAID'then p_paid_at else paid_at end,failed_at=case when p_status='FAILED'then now()else failed_at end,cancelled_at=case when p_status='CANCELLED'then now()else cancelled_at end,expired_at=case when p_status='EXPIRED'then now()else expired_at end,updated_at=now()where id=p.id;insert into payment_events(garage_id,payment_id,appointment_id,provider,event_type,metadata)values(p.garage_id,p.id,p.appointment_id,p.provider,event_name,'{}')on conflict do nothing;if p_status='PAID'then update appointments set status='CONFIRMED',updated_at=now()where id=p.appointment_id and garage_id=p.garage_id and status='AWAITING_PAYMENT';insert into appointment_events(garage_id,appointment_id,event_type,old_status,new_status,metadata)values(p.garage_id,p.appointment_id,'CONFIRMED','AWAITING_PAYMENT','CONFIRMED',jsonb_build_object('paymentId',p.id))on conflict do nothing;insert into notifications(garage_id,type,title,message,href,entity_type,entity_id)values(p.garage_id,'SYSTEM',case when p.payment_strategy='DEPOSIT'then'Acompte reçu'else'Paiement reçu'end,(p.amount_cents::numeric/100)::text||' '||p.currency,'/appointments/'||p.appointment_id,'payment',p.id);elsif p_status='EXPIRED'then update appointments set status='CANCELLED',updated_at=now()where id=p.appointment_id and status='AWAITING_PAYMENT';end if;return'applied';end $$;
revoke all on function public.apply_verified_payment(uuid,text,text,integer,text,boolean,timestamptz,jsonb)from public;
